# Generated by Django 3.2 on 2023-04-02 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='updatedAt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 4, 2, 13, 29, 49, 748284)),
            preserve_default=False,
        ),
    ]
